name: ğŸ—ƒï¸ Publish
on:
  push:
    tags:
      - 'v*'

env:
  GO_VERSION: 1.25.x
  SUPPORTED_ARCHITECTURES: ("amd64" "arm64")

jobs:
  publish:
    name: ğŸš€ Publish Fileman
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: ğŸšš Get latest code
        uses: actions/checkout@v4

      - name: ğŸ›  Setup Go ${{ env.GO_VERSION }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: ğŸ–¥ï¸ Display Go version
        run: go version

      - name: ğŸ§° Install dependencies
        run: go mod download

      - name: ğŸ§ Build Linux binaries
        run: |
          archs=${{ env.SUPPORTED_ARCHITECTURES }}
          for arch in "${archs[@]}"; do
            GOOS=linux GOARCH=$arch go build -o ./fileman_linux_$arch
          done

      - name: ğŸ Build macOS binaries
        run: |
          archs=${{ env.SUPPORTED_ARCHITECTURES }}
          for arch in "${archs[@]}"; do
            GOOS=darwin GOARCH=$arch go build -o ./fileman_macos_$arch
          done

      - name: ğŸªŸ Build Windows binaries
        run: |
          archs=${{ env.SUPPORTED_ARCHITECTURES }}
          for arch in "${archs[@]}"; do
            GOOS=windows GOARCH=$arch go build -o ./fileman_windows_$arch.exe
          done

      - name: ğŸ’¾ Upload Artifacts
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ./fileman_linux_*
            ./fileman_macos_*
            ./fileman_windows_*