name: ğŸ§ Tests
on:
  push:
      branches:
      - main
  pull_request:
      branches:
      - main

env:
  GO_VERSION: 1.25.x

jobs:
  test:
    name: ğŸ“ Test Fileman
    runs-on: ubuntu-latest
    steps:
      - name: ğŸšš Get latest code
        uses: actions/checkout@v4
      - name: ğŸ›  Setup Go ${{ env.GO_VERSION }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: ğŸ–¥ï¸ Display Go version
        run: go version
      - name: ğŸ§° Install dependencies
        run: go mod download
      - name: ğŸ— Build
        run: go build -v ./...
      - name: ğŸ”¬ Test with the Go CLI
        run: go test -json > TestResults.json
      - name: ğŸ“¤ Upload Test Results
        uses: actions/upload-artifact@v4
        with:
          name: Go-Results
          path: TestResults.json